class Solution {
    fun solution(a: Int, b: Int): String {
        val day = arrayOf(arrayOf("FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU", 
                                  "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU",
                                  "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU",
                                  "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"),
        arrayOf("MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON"),
        arrayOf("TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON",
                "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON",
                "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON",
                "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU"),
        arrayOf("FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU",
                "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU",
                "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU",
                "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"),
        arrayOf("SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT",
                "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT",
                "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT",
                "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON", "TUE"),
        arrayOf("WED", "THU", "FRI", "SAT", "SUN", "MON", "TUE",
                "WED", "THU", "FRI", "SAT", "SUN", "MON", "TUE",
                "WED", "THU", "FRI", "SAT", "SUN", "MON", "TUE",
                "WED", "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU"),
        arrayOf("FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU",
                "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU",
                "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU",
                "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"),
        arrayOf("MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN",
                "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED"),
        arrayOf("THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED",
                "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED",
                "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED",
                "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI"),
        arrayOf("SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI",
                "SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI",
                "SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI",
                "SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON"),
        arrayOf("TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON",
                "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON",
                "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON",
                "TUE", "WED", "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED"),
        arrayOf("THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED",
                "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED",
                "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED",
                "THU", "FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"))
        
        return day[a-1][b-1]
    }
}